
apiVersion: v1
kind: Service
metadata:
  name: local-registry
  namespace: book-author
spec:
  selector:
    app: local-docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
